export { AutenticarJWT } from './VerificarToken'
export { upload } from './multerSubirArchivos'
export { getUltimoRegistro } from './getUltimoRegistro'
export { validarID } from './validarID'
export { validarColeccionValida } from './validarColeccionValida'